// @generated by protoc-gen-es v1.10.0
// @generated from file api/tasks/v1/tasks.proto (package api.tasks.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, FieldMask, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Timestamp } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message api.tasks.v1.Task
 */
export declare class Task extends Message<Task> {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: google.protobuf.Timestamp deadline = 4;
   */
  deadline?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp completed_at = 5;
   */
  completedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 1000;
   */
  createTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp update_time = 1001;
   */
  updateTime?: Timestamp;

  constructor(data?: PartialMessage<Task>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "api.tasks.v1.Task";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Task;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Task;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Task;

  static equals(a: Task | PlainMessage<Task> | undefined, b: Task | PlainMessage<Task> | undefined): boolean;
}

/**
 * @generated from message api.tasks.v1.CreateTaskRequest
 */
export declare class CreateTaskRequest extends Message<CreateTaskRequest> {
  /**
   * Task is the the task to create.
   *
   * @generated from field: api.tasks.v1.Task task = 2;
   */
  task?: Task;

  constructor(data?: PartialMessage<CreateTaskRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "api.tasks.v1.CreateTaskRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateTaskRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateTaskRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateTaskRequest;

  static equals(a: CreateTaskRequest | PlainMessage<CreateTaskRequest> | undefined, b: CreateTaskRequest | PlainMessage<CreateTaskRequest> | undefined): boolean;
}

/**
 * @generated from message api.tasks.v1.DeleteTaskRequest
 */
export declare class DeleteTaskRequest extends Message<DeleteTaskRequest> {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  constructor(data?: PartialMessage<DeleteTaskRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "api.tasks.v1.DeleteTaskRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteTaskRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteTaskRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteTaskRequest;

  static equals(a: DeleteTaskRequest | PlainMessage<DeleteTaskRequest> | undefined, b: DeleteTaskRequest | PlainMessage<DeleteTaskRequest> | undefined): boolean;
}

/**
 * @generated from message api.tasks.v1.UndeleteTaskRequest
 */
export declare class UndeleteTaskRequest extends Message<UndeleteTaskRequest> {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  constructor(data?: PartialMessage<UndeleteTaskRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "api.tasks.v1.UndeleteTaskRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UndeleteTaskRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UndeleteTaskRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UndeleteTaskRequest;

  static equals(a: UndeleteTaskRequest | PlainMessage<UndeleteTaskRequest> | undefined, b: UndeleteTaskRequest | PlainMessage<UndeleteTaskRequest> | undefined): boolean;
}

/**
 * @generated from message api.tasks.v1.UpdateTaskRequest
 */
export declare class UpdateTaskRequest extends Message<UpdateTaskRequest> {
  /**
   * @generated from field: api.tasks.v1.Task task = 1;
   */
  task?: Task;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask;

  constructor(data?: PartialMessage<UpdateTaskRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "api.tasks.v1.UpdateTaskRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateTaskRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateTaskRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateTaskRequest;

  static equals(a: UpdateTaskRequest | PlainMessage<UpdateTaskRequest> | undefined, b: UpdateTaskRequest | PlainMessage<UpdateTaskRequest> | undefined): boolean;
}

/**
 * @generated from message api.tasks.v1.GetTaskRequest
 */
export declare class GetTaskRequest extends Message<GetTaskRequest> {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  constructor(data?: PartialMessage<GetTaskRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "api.tasks.v1.GetTaskRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetTaskRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetTaskRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetTaskRequest;

  static equals(a: GetTaskRequest | PlainMessage<GetTaskRequest> | undefined, b: GetTaskRequest | PlainMessage<GetTaskRequest> | undefined): boolean;
}

/**
 * @generated from message api.tasks.v1.ListTasksRequest
 */
export declare class ListTasksRequest extends Message<ListTasksRequest> {
  /**
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 3;
   */
  pageToken: string;

  constructor(data?: PartialMessage<ListTasksRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "api.tasks.v1.ListTasksRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListTasksRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListTasksRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListTasksRequest;

  static equals(a: ListTasksRequest | PlainMessage<ListTasksRequest> | undefined, b: ListTasksRequest | PlainMessage<ListTasksRequest> | undefined): boolean;
}

/**
 * @generated from message api.tasks.v1.ListTasksResponse
 */
export declare class ListTasksResponse extends Message<ListTasksResponse> {
  /**
   * @generated from field: repeated api.tasks.v1.Task tasks = 1;
   */
  tasks: Task[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;

  constructor(data?: PartialMessage<ListTasksResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "api.tasks.v1.ListTasksResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListTasksResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListTasksResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListTasksResponse;

  static equals(a: ListTasksResponse | PlainMessage<ListTasksResponse> | undefined, b: ListTasksResponse | PlainMessage<ListTasksResponse> | undefined): boolean;
}

