apiVersion: v1
kind: Service
metadata:
  name: todo
  labels:
    app.kubernetes.io/name: todo
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: v1
spec:
  selector:
    app.kubernetes.io/name: todo
    app.kubernetes.io/version: v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080