swagger: "2.0"
info:
  title: Todo API
  description: A web service written in Go, showcasing various features and technologies used in real world production-grade applications.
  version: "0.8"
  contact:
    name: Marcos Huck
    url: https://github.com/marcoshuck
    email: marcos@huck.com.ar
  license:
    name: MIT License
    url: https://github.com/marcoshuck/todo/blob/main/LICENSE
tags:
  - name: TasksWriterService
  - name: TasksReaderService
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/tasks:
    get:
      summary: ListTasks returns a list of Tasks.
      operationId: TasksReaderService_ListTasks
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1ListTasksResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: pageSize
          in: query
          required: false
          type: integer
          format: int32
        - name: pageToken
          in: query
          required: false
          type: string
      tags:
        - TasksReaderService
    post:
      summary: CreateTask creates a Task.
      operationId: TasksWriterService_CreateTask
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1Task'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: task
          description: Task is the the task to create.
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1Task'
            required:
              - task
      tags:
        - TasksWriterService
  /v1/tasks/{id}:
    get:
      summary: GetTask returns a Task.
      operationId: TasksReaderService_GetTask
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1Task'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
          format: int64
      tags:
        - TasksReaderService
    delete:
      operationId: TasksWriterService_DeleteTask
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1Task'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
          format: int64
      tags:
        - TasksWriterService
  /v1/tasks/{task.id}:
    patch:
      operationId: TasksWriterService_UpdateTask
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1Task'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: task.id
          in: path
          required: true
          type: string
          format: int64
        - name: task
          in: body
          required: true
          schema:
            type: object
            properties:
              title:
                type: string
              description:
                type: string
              deadline:
                type: string
                format: date-time
              completedAt:
                type: string
                format: date-time
              createTime:
                type: string
                format: date-time
              updateTime:
                type: string
                format: date-time
      tags:
        - TasksWriterService
  /v1/tasks:undelete:
    post:
      operationId: TasksWriterService_UndeleteTask
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1Task'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1UndeleteTaskRequest'
      tags:
        - TasksWriterService
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1ListTasksResponse:
    type: object
    properties:
      tasks:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Task'
      nextPageToken:
        type: string
  v1Task:
    type: object
    properties:
      id:
        type: string
        format: int64
      title:
        type: string
      description:
        type: string
      deadline:
        type: string
        format: date-time
      completedAt:
        type: string
        format: date-time
      createTime:
        type: string
        format: date-time
      updateTime:
        type: string
        format: date-time
  v1UndeleteTaskRequest:
    type: object
    properties:
      id:
        type: string
        format: int64
    required:
      - id
externalDocs:
  description: README
  url: https://github.com/marcoshuck/todo/blob/main/README.md
