name: E2E Tests
on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - v*
jobs:
  e2e:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start containers
        run: make ci/compose-up

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install E2E Browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: npx playwright test

      - name: Stop containers
        if: always()
        run: make ci/compose-down

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report
          path: playwright-report/
          retention-days: 10
